name: Authenticate to Google Cloud

on:
  workflow_call:

jobs:
  auth:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/181853912506/locations/global/workloadIdentityPools/github-pool-v3/providers/github-provider-v3'
          service_account: 'gemini-cicd-agent-v2@bestpgindighi-in.iam.gserviceaccount.com'
