name: CI/CD 

on:  push:    branches: [ walking-skeleton ]

env:  PROJECT_ID: fir-bestpg  REGION: asia-south1  REPOSITORY: cloud-run  SERVICE: api-backend  # Tag with the commit SHA  IMAGE: asia-south1-docker.pkg.dev/fir-bestpg/cloud-run/api-backend:${{ github.sha }}

jobs:  build-and-deploy:    runs-on: ubuntu-latest    permissions:      contents: read      id-token: write

    steps:      - name: Checkout        uses: actions/checkout@v4

      - name: Auth to Google Cloud (JSON key)        uses: google-github-actions/auth@v2        with:          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud        uses: google-github-actions/setup-gcloud@v2        with:          version: '>= 471.0.0'

      - name: Configure Docker to use Artifact Registry        run: gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Build image        run: |          # Dockerfile is at repo root; context is '.'          docker build --platform linux/amd64 -t "$IMAGE" .

      - name: Push image        run: docker push "$IMAGE"

      - name: Deploy to Cloud Run        run: |          gcloud run deploy "$SERVICE" \            --image "$IMAGE" \            --region "$REGION" \            --platform managed \            --allow-unauthenticated \            --port 8080 \            --quiet

      - name: Output service URL        run: |          gcloud run services describe "$SERVICE" \            --region "$REGION" \            --format='value(status.url)'
