# This workflow builds and deploys the project to Firebase.

name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main
      - walking-skeleton
      - walking-skeleton

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Frontend Dependencies & Build
        run: |
          cd src/internal_dashboard/frontend
          npm install
          npm run build

      - name: Setup Firebase Tools
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: ${{ env.PROJECT_ID }}
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
