name: Deploy to Cloud Run

on:
  push:
    branches: [walking-skeleton]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}   # fir-bestpg
  GAR_LOCATION: asia            # or asia-south1 — must match the repo
  RUN_REGION: asia-south1       # Cloud Run region
  SERVICE_NAME: api-backend
  REPO: cloud-run

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true  # <-- critical

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Who am I?
        run: |
          gcloud auth list --filter=status:ACTIVE
          gcloud config get-value project
          # Also verify ADC is usable:
          gcloud auth application-default print-access-token | head -c 20; echo

      - name: Describe GAR repo
        run: |
          gcloud artifacts repositories describe ${{ env.REPO }} \
            --location=${{ env.GAR_LOCATION }} \
            --project=${{ env.PROJECT_ID }}

      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet

      - name: Docker login (defensive)
        run: |
          gcloud auth print-access-token | \
            docker login -u oauth2accesstoken --password-stdin \
            https://${{ env.GAR_LOCATION }}-docker.pkg.dev

      - id: vars
        name: Compute image URI
        run: |
          echo "image_uri=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build
        run: docker build -t ${{ steps.vars.outputs.image_uri }} .

      - name: Push
        run: docker push ${{ steps.vars.outputs.image_uri }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.RUN_REGION }}        # <-- NOT "asia"
          image: ${{ steps.vars.outputs.image_uri }}
          allow_unauthenticated: true
