name: Deploy Full Stack to Firebase and Cloud Run

on:
  push:
    branches:
      - walking-skeleton

jobs:
  build-and-deploy-backend:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Create Artifact Registry repository if it doesn't exist
        run: |
          gcloud artifacts repositories describe api-backend --location=asia-south1 >/dev/null 2>&1 || \
          gcloud artifacts repositories create api-backend \
            --repository-format=docker \
            --location=asia-south1 \
            --description="Repository for the main backend API"

      - name: Configure Docker
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/api-backend/main:latest .
          docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/api-backend/main:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy api-backend \
            --image=asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/api-backend/main:latest \
            --region=asia-south1 \
            --platform=managed \
            --allow-unauthenticated

  deploy-frontend:
    name: Deploy Frontend
    needs: build-and-deploy-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --project ${{ secrets.GCP_PROJECT_ID }} --only hosting -m "Deploy from GitHub Actions"
