# This workflow builds and deploys the project to Firebase.

name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main
      - walking-skeleton
      - walking-skeleton-v3

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Frontend Dependencies & Build
        run: |
          cd src/internal_dashboard/frontend
          npm install
          npm run build

      - name: Setup Firebase Tools
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: ${{ env.PROJECT_ID }}

      

      - name: Deploy to Firebase
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting,functions --project ${{ env.PROJECT_ID }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}